Nearby inst
ToriBench/wethink-central-application pull request #74
Opened 2022-02-23 10:51 UTC by aaronsh1

Updated the logic in the uspStudentEligible Stored Proc and added in if they want to check in the city the student lives in.

2022-02-23 11:16 UTC, mothupir requested changes
Can you convert the city for student and institution to either lower case or upper case before comparing them

2022-02-23 12:13 UTC, mothupir approved these changes

2022-02-23 13:08 UTC, mothupir approved these changes

2022-02-23 13:57 UTC, ToriBench commented on DML/StoredProcedures/ProcStudentEligible.sql
> +				Addresses.AddressID = Institutions.InstitutionID
I don't really understand this line. When would an address ID = Institution ID?

2022-02-24 06:40 UTC, ToriBench approved these changes

2022-02-24 06:59 UTC, mothupir approved these changes

2022-02-24 06:59 UTC, merged