Updated PopulateDB.sql to include the new tables
ToriBench/wethink-central-application pull request #75
Opened 2022-02-23 14:19 UTC by IKalonji2

Updated PopulateDB.sql to include the new tables

2022-02-23 14:29 UTC, mothupir requested changes
Can you modify the data insertion for User and Student to match the definitions of the these tables

2022-02-23 15:02 UTC, IKalonji2 commented
Fixed that, used the wrong script to create the DB. My bad.


Issa Kalonji | Junior Software Engineer
E ***@***.*** T +27 11 532 8300 M +27  67 060 3338 W www.bbdsoftware.com<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.bbdsoftware.com%2F&data=04%7C01%7Cissa%40bbd.co.za%7C9ccc3669d38446895fe808d9d1ab11b2%7Ccccbf5026b9140d6be025ffa0eb711d6%7C1%7C0%7C637771354954486539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Sq4AlAy1Lmf3pqvnvoz9%2BOjHHggQ2%2F%2BKFtXCfj84Pm8%3D&reserved=0>
***@***.***


This email is confidential and subject to the disclaimer on the BBD website.


From: ***@***.***>
Sent: Wednesday, 23 February 2022 16:29
To: ***@***.***>
Cc: Issa ***@***.***>; ***@***.***>
Subject: Re: [ToriBench/wethink-central-application] Updated PopulateDB.sql to include the new tables (PR #75)


@mothupir requested changes on this pull request.

Can you modify the data insertion for User and Student to match the definitions of the these tables

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FToriBench%2Fwethink-central-application%2Fpull%2F75%23pullrequestreview-891163432&data=04%7C01%7Cissa%40bbd.co.za%7C2b494fa7ae9b40e535d608d9f6d8f4c7%7Ccccbf5026b9140d6be025ffa0eb711d6%7C1%7C0%7C637812233969738717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Iidk0TQ8NmdK9XbmTXJ257ZqM12skGa%2FAt62hrzIRp4%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXYIK5FOL5XDDH75QQ5DIS3U4TVN7ANCNFSM5PEPWEZQ&data=04%7C01%7Cissa%40bbd.co.za%7C2b494fa7ae9b40e535d608d9f6d8f4c7%7Ccccbf5026b9140d6be025ffa0eb711d6%7C1%7C0%7C637812233969738717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lYt0ZClNdSzU28OZOOmyghtnPYe6pBA%2BhdlQn3NL9fI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cissa%40bbd.co.za%7C2b494fa7ae9b40e535d608d9f6d8f4c7%7Ccccbf5026b9140d6be025ffa0eb711d6%7C1%7C0%7C637812233969738717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QTs4XZE0F%2FOK918Yd%2BrjHEHKaOkckGFO2k80P%2FJarx8%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cissa%40bbd.co.za%7C2b494fa7ae9b40e535d608d9f6d8f4c7%7Ccccbf5026b9140d6be025ffa0eb711d6%7C1%7C0%7C637812233969738717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q2StH0304gLZnB%2FMm%2B%2BC1w37NUycys9Rssibl5V%2BTRY%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-02-23 15:38 UTC, mothupir requested changes
change the data you're inserting to user and student as it does not match the columns

2022-02-24 06:57 UTC, mothupir approved these changes

2022-02-24 06:57 UTC, merged